import type { Metadata } from "next";
import localFont from "next/font/local";
import { MotionProvider } from "@/components/motion/MotionProvider";
import "./globals.css";

/* Self-hosted via next/font/local (Task 3.12). The previous next/font/google
   loaders compiled a fallback-only font module during an offline moment —
   Turbopack's persistent dev cache kept serving it, so no @font-face for
   "Geist" ever reached the browser and every Geist slot rendered Arial.
   next/font/local reads the woff2 files from app/fonts/ directly: no
   build-time network, no cache to go stale, and the loader's own error
   message prescribes it for exactly this failure. The files are the full
   variable faces from the official geist package (all glyphs, not the
   Google-subset cuts): the rendered copy includes U+2192 (→) in the file
   converters' labels, and Google's latin/latin-ext subset files omit that
   one codepoint — the full faces are the §5 "widen the subset" repair.
   Weight range 100 900 matches the variable axes. */
const geistSans = localFont({
  src: [{ path: "./fonts/Geist-Variable.woff2", weight: "100 900", style: "normal" }],
  variable: "--font-geist-sans",
  display: "swap",
  preload: true,
});

const geistMono = localFont({
  src: [{ path: "./fonts/GeistMono-Variable.woff2", weight: "100 900", style: "normal" }],
  variable: "--font-geist-mono",
  display: "swap",
  preload: true,
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Runs before first paint, as the body's first element: an inline script is
 * parser-blocking, so the theme class is on `<html>` before anything can
 * paint — no flash of the wrong theme. Dark is the default: the server
 * renders `class="dark"` outright and this script's only job is to remove it
 * when the stored choice says "light", so a first visit never depends on a
 * system preference and a stored "dark" needs no work at all.
 */
const themeBootScript = `try{if(localStorage.getItem("unipilot-theme")==="light"){document.documentElement.classList.remove("dark")}}catch(e){}`;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      // `globals.css` sets `scroll-behavior: smooth` on `html` (behind
      // `prefers-reduced-motion: no-preference`) so in-page anchor jumps glide.
      // Next.js has to scroll to the top on every route change, and with smooth
      // scrolling on it *animates* that jump — the reader watches the old page
      // scroll away while `RouteTransition` is already playing the new one in.
      // This attribute tells Next.js the smooth behaviour is deliberate so it
      // can suspend it for the duration of a route change and restore it after:
      // anchors keep gliding, navigations land instantly. Without it Next.js
      // logs a warning on every soft navigation.
      data-scroll-behavior="smooth"
      // `dark` is the pre-paint default; the boot script below may remove it
      // for a returning light-theme visitor before React hydrates, which is a
      // deliberate pre-hydration DOM mutation React must not warn about.
      className={`dark ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <script dangerouslySetInnerHTML={{ __html: themeBootScript }} />
        <MotionProvider>{children}</MotionProvider>
      </body>
    </html>
  );
}
